osfclient/osfclient

osfclient/__main__.py, osfclient/cli.py, osfclient/tests/test_cli.py, osfclient/tests/test_listing.py
=> [MRG] Add support for a local config file

README.md, setup.py
Fixes #27 
Updating the command-line examples in the README
=> [MRG] Update README

osfclient/__main__.py
Fixes #29 
Add help message and description, `osf` now prints the help message when run without arguments
=> Help message when run without arguments

setup.py
I tried to install `osfclient` with
`$ pip install https://github.com/dib-lab/osf-cli/archive/master.tar.gz`
When I try to run it, I get an ImportError:
```$ osf
File "/usr/lib/python3.5/site-packages/osfclient/api.py", line 1, in <module>
from .models import OSFCore
ImportError: No module named 'osfclient.models'
```
Seems like the issue is the `packages` field, it is not including all the modules in the package (like `osfclient.models`). I used `find_packages` to do this automatically.
=> [MRG] Fix package discovery

osfclient/models/storage.py, osfclient/tests/test_storage.py
Fixes #32
This seems like a bug in `requests` which sends a `Transfer-encoding: chunked` header but doesn't do anything for zero length files?
By `peek`ing at the file to see if there is anything in it we (I think) can detect empty files and then pass an empty byte string to `requests` which seems to work.
=> Special casing zero length files

CONTRIBUTING.md
Simplez. Thanks to [@stephwright](https://github.com/mozilla/global-sprint/issues/123#issuecomment-305208712)
=> [MRG] Fix typo in license link

README.rst, docs/index.rst
Added the GH link to the readthedocs front page and the intro materials of OSF to the README + readthedocs.
=> add links to GH & intro materials (closes #85 & #82)

osfclient/models/storage.py, osfclient/tests/test_storage.py, osfclient/tests/test_utils.py, osfclient/utils.py
Fixes #75 
In python 2 there is no `peek()`, so implemented our own.
Does someone know why `six` does not have a compatibility thing for this?
=> [WIP] Fix check for empty file when on python 2

osfclient/__main__.py, osfclient/cli.py, osfclient/tests/mocks.py, osfclient/tests/test_uploading.py
Fixes #18 
This will allow people to upload a whole directory and all files in it. Modelled on how `scp` works. An alternative would be to detect that the `source` is a directory and infer that the user meant to upload everything recursively.
=> [MRG] Recursively upload files

docs/cli-usage.rst
Setting up, noticed that `ls` was at some point changed to `list` -- as per the super helpful command line feedback!
=> change ls to list in getting started docs

osfclient/api.py, osfclient/models/project.py, osfclient/tests/fake_responses.py, osfclient/tests/test_api.py
Utilizes a redirect in APIv2 to avoid osf-cli needing to know whether a GUID refers to a `node` or a `registration` object.
Manually tested to verify this:
1) works
2) does not break file uploads.
Introduces a small side effect: provide a file GUID, and it breaks. It would have broken before, this just makes it break in a different place.
=> Add clone support for registrations

osfclient/models/file.py
Getting the hashes for each file from the metadata would be really useful (e.g. check for file corruption or avoiding redownloading)
Apparently there is no tests checking the attributes associated with the file so I did not added a test.
@betatim Let me know it the change would make sense?
=> [MRG] EHN: provide the file hashes publicly

osfclient/models/storage.py
If server breaks connection, proceed with update if user specifies --force option.
Fixes #133
Note: if the server breaks the connection we infer that this is due to the combination of a large file and resource already being present. This is not actually guaranteed, so raising `FileExistsError` could potentially result in misdirecting users. Perhaps additional reporting required?
=> [MRG] Fixes bug preventing updates on large files

README.rst
This adds the travis badge to the README. The main purpose of the PR is to reactivate travis that had become disabled about 9months ago. Not sure what went wrong there.
=> [MRG] Add travis badge to README

.travis.yml
I don't know if there's a reason to leave `dib-lab/osf-cli` as the deploy repo in `.travis.yml` instead of `osfclient/osfclient`, but the travis error [here](https://travis-ci.org/osfclient/osfclient/jobs/409185936#L865) makes it seem like the change is necessary, and making the change seemed to fix the problem [here](https://travis-ci.org/benlindsay/osfclient/builds/409188104)
=> changed deploy repo from dib-lab/osf-cli to osfclient/osfclient

.travis.yml
Follow up #153 
The idea behind uploading to test PyPI on every merged PR is that we get to exercise the deploy step. Instead of only finding out when we make a release that the deploy setup is broken.
I am not sure it is a good idea to keep doing this and if we keep having trouble I would vote to remove this instead of trying to fix it (I think) :-/
=> [MRG] Update test PyPI URL used by Travis deploy step

README.rst
@betatim Is this kind of what you meant in #157 by the following?
>We can add a sentence to the README stating what secrets there are, who they've been shared with and what to do if one wants to get a copy.
I'm not sure what other secrets there are that might be necessary to share, or if you had in mind more robust ideas for managing project secrets, or if I'm missing people who should be on the list. Let me know if this is all way off.
=> [WIP] added info about secrets to README.rst

osfclient/models/file.py, osfclient/models/session.py
Was trying to use URLs like `https://osf.io/download/4rfew/`
Now this style:
`https://files.osf.io/v1/resources/fwefw/providers/osfstorage/5ee88fsdfafe0040c4a3b3`
Which happens to be the same as the upload URL.
Fixes https://github.com/osfclient/osfclient/issues/172
Fixes https://github.com/osfclient/osfclient/issues/144
=> Fix file access URL for downloads (replaces #176)

osfclient/models/core.py, osfclient/models/session.py
I have searched for a way to update an existing OSF project (e.g., description, tags, category, ...) from within a script and couldn't find a way with the existing source code (I may have missed it, so please let me know if there is another, already implemented way to do this). This PR adds support for patching a resource, and thus lays the ground work for updating nodes via PATCH request.
=> New Feature: implement http patch method in OSF session

osfclient/api.py, osfclient/cli.py, osfclient/models/session.py, osfclient/tests/test_removing.py, osfclient/tests/test_uploading.py
* Personal access token support was added in #181, but our write
methods (upload & remove) were using obsolete logic to validate
write support.  Update `session` object to track whether auth was
successful rather than what parameters were passed.
* Update validation failure messages for upload/remove along with
relevant tests.
* Allow the `OSF` object to track the given token.  This is not
currently needed, but is provided to maintain symmetry with the
current username & password behavior.
=> [CR] Support token auth for write commands

README.rst, docs/cli-usage.rst, osfclient/__main__.py, osfclient/cli.py, osfclient/models/file.py, osfclient/tests/mocks.py, osfclient/tests/test_listing.py
Proposed: `-l` or `--long`, analogous to unix `ls`, for #118 
This is to show the `guid`, which is the 5 letter code after osf.io. Download URLs can be formed from `osf.io/{guid}/download`. This is useful to make a mapping between logical file names and download URLs
TBD:
* what other properties to show?
* allow other separator than `,`? Escape `,`s in filenames (because people)
BUGS:
sometimes the OSF API will return `None` for guids for files, even if they are there in the web interface. Need to check API docs more then contact support if required.
Note:
original proposal was to extend the upload command, but this doesn't seem to return guids and putting this on `list` seems more generally useful.
=> WIP: Add option to show guids on list command
