osfclient/osfclient

osfclient/__init__.py
osfclient/__main__.py
osfclient/filetree.py
requirements.txt

* adds `-u/--username`
* `python -m osfclient ls 7g6vu` and `python -m osfclient fetch 7g6vu` work as expected.

add authentication options, get ls and fetch both working

---

.gitignore
.travis.yml
README.md
build_tools/travis_install.sh
devRequirements.txt
osfclient/__init__.py
osfclient/__main__.py
osfclient/tests/test_listing.py
setup.py

Adding a test and some infrastructure to run it.

[MRG] First test!

---

osfclient/__main__.py
osfclient/cli.py
osfclient/tests/test_listing.py

Merge after #11 
Fetch API password from environment instead of a file.

[WIP] Password from env

---

osfclient/tests/mocks.py
osfclient/tests/test_fetching.py
osfclient/tests/test_listing.py

Test the `osf fetch` command line.
Waiting for #11

[MRG] Test fetch cli

---

.coveragerc
osfclient/__main__.py
osfclient/cli.py
osfclient/exceptions.py
osfclient/models/__init__.py
osfclient/models/core.py
osfclient/models/file.py
osfclient/models/session.py
osfclient/models/storage.py
osfclient/tests/fake_responses.py
osfclient/tests/mocks.py
osfclient/tests/test_file.py
osfclient/tests/test_listing.py
osfclient/tests/test_session.py
osfclient/tests/test_storage.py
osfclient/tests/test_uploading.py
osfclient/tests/test_utils.py
osfclient/utils.py

Add support for uploading a file to any of the currently active storages for a project.
Need to decide how to handle non-existent folders in the path of a file. Create them or error out and require explicit creation or error by default but have a `mkdirs -p` equivalent flag?

[MRG] Upload files

---

README.md

[WIP] Add basic usage information for the CLI

---

README.md
osfclient/__main__.py
osfclient/cli.py
osfclient/tests/mocks.py
osfclient/tests/test_cloning.py
osfclient/tests/test_fetching.py
osfclient/tests/test_uploading.py

Fixes #17 
This adds the `osf fetch` command which let's you fetch a single file by path.

[MRG] Fetch a single file

---

osfclient/__main__.py
osfclient/cli.py

Documents the functions and generates help messages for the CLI interface.

Move documentation from argument parser to function definitions

---

README.md
devRequirements.txt
osfclient/__main__.py
osfclient/api.py
osfclient/cli.py
osfclient/models/core.py
osfclient/models/file.py
osfclient/tests/mocks.py
osfclient/tests/test_cli.py
osfclient/tests/test_fetching.py
osfclient/tests/test_file.py
osfclient/tests/test_removing.py
osfclient/tests/test_uploading.py

Remove a file from the remote storage.

[WIP] Remove a file from remote storage

---

osfclient/tests/test_cloning.py

Mock makedirs as well to prevent spurious directories

---

CONDUCT.md
CONTRIBUTING.md
README.md

Make it more obvious how to contribute to this project.

[MRG] Add contributing guidelines

---

osfclient/__main__.py
osfclient/tests/test_main.py

Start adding tests for the CLI interface

[MRG] Add tests for main entry point

---

README.md
osfclient/cli.py
osfclient/tests/test_cli.py

Prompt user for password when OSF_PASSWORD is not set.

---

.travis.yml
build_tools/travis_install.sh
devRequirements.txt
osfclient/__main__.py
osfclient/cli.py
osfclient/models/core.py
osfclient/models/session.py
osfclient/models/storage.py
osfclient/tests/mocks.py
osfclient/tests/test_api.py
osfclient/tests/test_cli.py
osfclient/tests/test_cloning.py
osfclient/tests/test_fetching.py
osfclient/tests/test_file.py
osfclient/tests/test_listing.py
osfclient/tests/test_main.py
osfclient/tests/test_project.py
osfclient/tests/test_removing.py
osfclient/tests/test_session.py
osfclient/tests/test_storage.py
osfclient/tests/test_uploading.py
osfclient/utils.py

* Use mock for both python2 & python3
* Modify some cli code to run osf
* Update mock imports
* Add python 2.7 in travis

Run tests on Python 2.7

---

osfclient/__main__.py
osfclient/cli.py
osfclient/models/file.py
osfclient/tests/mocks.py
osfclient/tests/test_fetching.py
osfclient/tests/test_file.py
osfclient/tests/test_uploading.py
requirements.txt
setup.py

Fix #55 and adds progres bars.
This is a bit of a mishmash as it adds new features and fixes a bug.
Need to think about what test would have caught the streaming bug.

[MRG] Progress bars

---

osfclient/tests/test_cloning.py

Bit of a mystery to me why this only showed up now.

[MRG] Fix osf clone test that was asking for a password

---

osfclient/cli.py
osfclient/tests/test_cli.py
osfclient/tests/test_cloning.py
osfclient/tests/test_fetching.py
osfclient/tests/test_utils.py
osfclient/utils.py

Some more fixes for python 2 compatibility

[MRG] Python2 fixups

---

.gitignore
osfclient/__main__.py
osfclient/cli.py
osfclient/tests/test_cli.py

So, here's the first version of #43, totally without tests right now. Actually: I've never done any in Python. So a pointer would be highly appreciated!

[MRG] added `osf init` (feature for #43)

---

osfclient/__main__.py
osfclient/cli.py
osfclient/models/file.py
osfclient/models/storage.py
osfclient/tests/mocks.py
osfclient/tests/test_fetching.py
osfclient/tests/test_storage.py
osfclient/tests/test_uploading.py

Fixes #19 
Gives people the ability to update an existing file.
[WIP] <- still work in progress

[MRG] Adds support for updating an existing file

---

CONTRIBUTING.md
README.md
devRequirements.txt

Fixes #67 by adding a few more sentences and explicit install instructions (I was looking for those and disappointed I couldn't copy and paste!)
I will open a new issue to track "adding instructions on creating a new test". I think that might end up a little like this: http://imgur.com/gallery/Aru42om

[MRG] Update dev setup instructions and explain rebase policy

---

.travis.yml
requirements.txt
setup.py

Adding a section to deploy to test PyPI on every merge to give us an easier way to work out why this didn't work https://travis-ci.org/dib-lab/osf-cli/jobs/246226270
Also adds a missing dependency.

Travis deploy again

---

osfclient/cli.py
osfclient/tests/test_cli.py

Fixes #77
Print a nice error message when the user is not authorized to access a
project on the OSF or if they forgot to provide a username.

[MRG] Add decorator to handle Unauthorized exceptions

---

docs/index.rst

Whops, my bad regarding the broken links pointed out in #90. Should be fixed with this.

fix links, closes #90

---

osfclient/tests/test_utils.py
osfclient/utils.py

Adds one of the storage providers needed for #84.

[MRG] Add figshare as a storage provider

---

osfclient/tests/test_utils.py
osfclient/utils.py

Inspired by @ethanwhite: Another one for #84.

added googledrive to storage provider

---

osfclient/cli.py
osfclient/models/storage.py
osfclient/tests/test_uploading.py
osfclient/utils.py

fix for uploading subdirectories from windows

[MRG] windows directories

---

CONTRIBUTING.md

attempting to clarify my question for future developers

[MRG] all development done in a personal fork

---

README.rst
setup.py

Add long_description; fix header styling; add py36 classifier

---

README.rst

I just wanted to start out with an easier pull request to get my feet wet. Let me know if I should do anything differently if I make other pull requests in the future.

[MRG] update repo name in Contributing section of README

---

README.rst

Here's another little README modification proposal. How do we feel about adding this quick example for uploading a full directory? To me that's the most powerful feature of this tool, since there's no way to upload a full directory manually on the website.

[MRG] cleaned up readme a little and added directory upload example

---

osfclient/models/storage.py
osfclient/tests/test_storage.py
osfclient/utils.py

Fixes #133 
Here's my continuation of @cmungall's pull request #135. Should I add some tests for this?

[MRG] Fixes bug preventing updates on large files -- continuation of #135

---

README.rst

Previous PR #151 doesn't actually make a badge 😱

[MRG] Add a working badge

---

.travis.yml

Removing because it seems test.pypi.org no longer accepts uploads of already existing files. Decided to do this after #158 failed.

[MRG] removed test deploy configuration

---

README.rst

I edited the README to reflect that passwords are stored in Keybase git repo

[MRG] updated info about secrets

---

.travis.yml

@betatim I think this is the final thing we need to do to make this project not rely on your personal accounts. We won't be sure that I did the password thing right until we actually upload to PyPI (this is my first time doing this), but I'm pretty sure I did. I cloned osfclient/osfclient (as opposed to benlindsay/osfclient), ran  `travis encrypt password="<osfclient user password to pypi.org>"` and used the string it spat out.

[MRG] switched pypi user to osfclient

---

README.rst

I didn't realize this feature existed until browsing through the issues to see if anyone had asked for it!

Advertise fetch in README.rst
